site_name: MkDocs Translate

site_url: https://rei-vilo.github.io/MkDocs_Translate/
repo_url: https://github.com/rei-vilo/MkDocs_Translate/

theme:
    name: 'material'

extra:
    # https://pypi.org/project/mkdocs-google-translate/
    # pip install mkdocs-google-translate
    # See alternate: section
    alternate:
        # Original Language
      - name: English
        lang: 'en'
        link: '%GT_RELATIVE_URL%'  # For relative urls back to original language
        # Extra languages
      - name: Español
        lang: 'es'
        link: 'https://translate.goog/?_x_tr_sl=en&_x_tr_tl=es'
        # _x_tr_sl = source language
        # _x_tr_tl = translation language
      - name: Chinese
        lang: 'zh'
        link: 'https://translate.goog/?_x_tr_sl=en&_x_tr_tl=zh'
        # _x_tr_sl = source language
        # _x_tr_tl = translation language
      - name: Japanese
        lang: 'jp'
        link: 'https://translate.goog/?_x_tr_sl=en&_x_tr_tl=jp'


plugins:
  - search
    # https://pypi.org/project/mkdocs-google-translate/
    # pip install mkdocs-google-translate
    # See alternate: section
  - google-translate
#   - google-translate:
#       url: https://rei-vilo.github.io/MkDocs_Translate/


