site_name: MkDocs Translate

site_url: https://rei-vilo.github.io/MkDocs_Translate/
repo_url: https://github.com/rei-vilo/MkDocs_Translate/

theme:
    name: 'material'

extra:
    alternate:
    # https://pypi.org/project/mkdocs-google-translate/
    # pip install mkdocs-google-translate
    # Too old 2023, does not work: generates
    #     https://translate.goog/?_x_tr_sl=en&_x_tr_tl=es
    # instead of 
    #     https://<website>.translate.goog/userguide/index.html?_x_tr_sl=en&_x_tr_tl=fr
    alternate:
        # Original Language
      - name: English
        lang: 'en'
        link: '%GT_RELATIVE_URL%'  # For relative urls back to original language
        # Extra languages
      - name: Español
        lang: 'es'
        link: 'https://translate.goog/?_x_tr_sl=en&_x_tr_tl=es'
        # _x_tr_sl = source language
        # _x_tr_tl = translation language
